name: Kwiki-Autoformat
version: 0.01
abstract: Autoformat preformatted forms of text
author: Ian Langworth <langworth.com>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Kwiki: 0.30
  Text::Autoformat: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.33
